# Generated by Django 4.2.3 on 2023-07-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_trail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trail',
            name='state',
            field=models.CharField(default='Virginia', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trail',
            name='streetAddress',
            field=models.CharField(default='Roaring Run Road', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trail',
            name='zip',
            field=models.CharField(default=24085, max_length=100),
            preserve_default=False,
        ),
    ]
