# Generated by Django 4.2.3 on 2023-07-17 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_trail_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='image',
        ),
        migrations.AlterField(
            model_name='trail',
            name='map',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trail')),
            ],
        ),
        migrations.AddField(
            model_name='trail',
            name='images',
            field=models.ManyToManyField(related_name='trails', to='main_app.image'),
        ),
    ]
