# Generated by Django 4.2.3 on 2023-07-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='images',
        ),
        migrations.AddField(
            model_name='trail',
            name='image',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trail',
            name='map',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
