# Generated by Django 4.2.3 on 2023-07-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_trail_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='map',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
