# Generated by Django 4.2.3 on 2023-07-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='difficulty',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=[4], max_length=1),
        ),
    ]
