# Generated by Django 4.2.3 on 2023-07-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_remove_trail_map_alter_trail_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='difficulty',
        ),
    ]
